apiVersion: v1
kind: Pod
metadata:
  name: deployment-bonus
  labels:
    course: clo835
spec:
      containers:
      - name: webapp-container
        env:
        - name: APP_COLOUR
          value: "Purple"
        image: mmumshad/simple-webapp-color
        ports:
        - containerPort: 5000