apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-hostpath
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb
  storageClassName: localstorage
